### PR TITLE
disabling touch option

### PR DESCRIPTION
**Pull request by nikugogoi**
sliding the carousel with touch on touch enabled devices by setting mouse drag to false

### CODE REVIEW

**Comment by lsycxyj** [comment]
1. Please don't remove the eslint options
2. Some devices may have both mouse and touch events (eg. Windows Tablet)

**Comment by nikugogoi** [comment]
okay then i will pass a prop for enabling or disabling the sliding by touch

**Comment by nikugogoi** [comment]
@lsycxyj by the way.. i had to remove the esLint option as the linter was showing a syntax error in utils.js.... something about returning assignments

**Comment by nikugogoi** [comment]
i will be opening a new pull request

**Pull request closed without merging**
