### PR TITLE
Changed translate3d to translateX

### PR DESCRIPTION
**Pull request by lwestenberg**
Changed translate3d to translateX because translate3d results in blurry text inside the slides (https://stackoverflow.com/questions/8024061/webkit-blurry-text-with-css-scale-translate3d)

### CODE REVIEW

**Comment by lsycxyj** [comment]
`translateX` is much slower than `translate3d` :(

**Comment by lwestenberg** [comment]
Maybe add an option to choose between translateX or translate3d? E.g. in my case I have only 3 slides that contain mainly text and I notice no difference in speed when using translateX. The blurred text is clearly visible with translate3d however.

**Comment by lsycxyj** [comment]
Does [this](https://stackoverflow.com/questions/6411361/webkit-based-blurry-distorted-text-post-animation-via-translate3d/7477166#7477166) help? Or have you found any other solutions? I suppose adding an option is not a good solution.

**Comment by lwestenberg** [comment]
It seems to work! Thank you very much.

**Pull request closed without merging**
